const String WELCOME_TITLE = 'Welcome To\nNAME';
const String API_URL_LOGIN = "http://localhost:5000/api/users/login";
const String API_URL_REGISTER = "http://localhost:5000/api/users";
const String API_URL_USER_INFO = "http://localhost:5000/api/users/info";
const String API_URL_PLACES = "http://localhost:5000/api/places";
const String API_URL_CREATE_EVENT = "http://localhost:5000/api/events";
const String API_URL_GET_EVENTS = "http://localhost:5000/api/users/events";
const String API_URL_GET_USERS = "http://localhost:5000/api/users";
const int DESCRIPTION_CUTOFF = 140;
